@echo off
@set "PROJECT_ROOT=..\.."
@set "BUILD_ROOT=..\..\build"
@set "SERVER_ROOT=%BUILD_ROOT%\server"
@set "CONTENT_ROOT=%BUILD_ROOT%\content"
@set "TOOLS_ROOT=%PROJECT_ROOT%\tools"
@set "SQL_SERVER_TOOL=%TOOLS_ROOT%\sqliteadmin\sqliteadmin.exe"
@set "WEB_SERVER_URL=http://localhost:8080"
@set "WEB_SERVER_EXE=%SERVER_ROOT%\AsyncRPGWebServer.exe"
@set "TOOL_EXE=%SERVER_ROOT%\AsyncRPGDBTool.exe"
@set "DB_NAME=AsyncRPG"
@set "DB_PATH=%CONTENT_ROOT%"
@set "DB_FILE=%DB_PATH%\%DB_NAME%.db3"
@set "DB_CONNECTION_STRING=DbLinqProvider=Sqlite;DbLinqConnectionType=System.Data.SQLite.SQLiteConnection,System.Data.SQLite;Data Source=%DB_FILE%"
@set "MAP_TEMPLATE_PATH=%CONTENT_ROOT%\maps"
@set "MOB_DATA_PATH=%CONTENT_ROOT%\mobs"
@set "TEST_SCRIPT_FILE_PATH=%PROJECT_ROOT%\scripts\script_data\WebServiceTestScript.json"