@echo off
@set "PROJECT_ROOT=..\.."
@set "BUILD_ROOT=..\..\build"
@set "SERVER_ROOT=%BUILD_ROOT%\server"
@set "CONTENT_ROOT=%BUILD_ROOT%\content"
@set "SQL_SERVER_TOOLS_PATH=C:\Program Files\Microsoft SQL Server\100\Tools\Binn"
@set "TOOL_EXE=%SERVER_ROOT%\AsyncRPGDBTool.exe"
@set "DB_USERNAME=asyncrpg"
@set "DB_PASSWORD=password"
@set "DB_SERVER=localhost\SQLEXPRESS"
@set "DB_NAME=AsyncRPG"
@set "DB_CONNECTION_STRING=Data Source=%DB_SERVER%;Initial Catalog=%DB_NAME%;Trusted_Connection=Yes;"
@set "MAP_TEMPLATE_PATH=%CONTENT_ROOT%\maps"
@set "MOB_DATA_PATH=%CONTENT_ROOT%\mobs"
@set "TEST_SCRIPT_FILE_PATH=%PROJECT_ROOT%\scripts\script_data\WebServiceTestScript.json"